### ISSUE TITLE
is.redundant: Error: cannot allocate vector of size 250.0 Gb

### ISSUE THREAD

**Issue by sjain777** [mhahsler/arules#4] opened 2016-02-08 21:30 UTC
Hi, My arulesModel model contains 260K rules and has a size of 17 MB. Upon applying the is.redundant method, memory limit is reached on a machine with 16 GB RAM: 

is.redundant(arulesModel) 

Error: cannot allocate vector of size 250.0 Gb 
In addition: Warning messages: 
1: In .local(x, y, proper, sparse, ...) :   Reached total allocation of 16274Mb: see help(memory.size) 
2: In .local(x, y, proper, sparse, ...) :   Reached total allocation of 16274Mb: see help(memory.size) 
3: In .local(x, y, proper, sparse, ...) :   Reached total allocation of 16274Mb: see help(memory.size) 
4: In .local(x, y, proper, sparse, ...) :   Reached total allocation of 16274Mb: see help(memory.size)  

memory.limit() 
[1] 16274   # => 16 GB 

How to remove redundant rules without hitting the memory limit? Thanks!

**Comment by mhahsler** [comment] 2016-02-09 00:41
The issue is that the is redundant function needs to compare all rules with each other and thus needs O(n^2) space which obviously does not fit into memory in your case. A newer version of is.redundant will be released in the next version of arules that should be able to handle this better.

**Closed** 2016-02-09 14:48 UTC
Labels: enhancement

**Comment by sjain777** [comment] 2016-02-09 15:35
Thanks much for your feedback! I look forward to getting the new release.
